FROM ewolff/docker-java
COPY target/microservice-kubernetes-demo-customer-1.0-SNAPSHOT.jar .
CMD /usr/bin/java -Xmx400m -Xms400m -jar microservice-kubernetes-demo-customer-1.0-SNAPSHOT.jar
EXPOSE 8080
