apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: engdopdemo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: engdopdemo
    spec:
      containers:
      - name: engdopdemo-container
        image: engdopaksacr.azurecr.io/engdopdemo:img_id
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: engdopdemo
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: engdopdemo